[package]
name = "hyperspeedcube"
version = "0.2.0-dev"
authors = ["HactarCE"]
edition = "2021"
description = "Keyboard-driven multidimensional twisty puzzle simulator"
repository = "https://github.com/HactarCE/Hyperspeedcube/"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "4.0.1"
cgmath = "0.18"
glium = "0.30"
glium-glyph = "0.11"
itertools = "0.10"
imgui = { version = "0.8", features = ["tables-api"] }
imgui-glium-renderer = "0.8"
imgui-winit-support = "0.8"
key-names = { git = "https://github.com/HactarCE/key-names" }
lazy_static = "1.4"
png = "0.17"
rfd = "0.6"
send_wrapper = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
time = { version = "0.3", features = ["local-offset"] }
winit = { version = "*", features = ["serde"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]
FileDescription = "Hyperspeedcube"
ProductName = "Hyperspeedcube"
ProductVersion = "0.1.0"
OriginalFilename = "hyperspeedcube.exe"
LegalCopyright = "Copyright © 2022 HactarCE"
