[package]
name = "keyboard_speedcube"
version = "0.1.0"
authors = ["HactarCE"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18"
glium = "0.30"
lazy_static = "1.4"
send_wrapper = "0.5"
