---
log_file: puzzle.log
gfx:
  fps: 60
  font_size: 16.0
  msaa: "8"
  label_size: 24.0
view:
  Rubiks3D:
    theta: 35.0
    phi: 0.0
    scale: 1.25
    fov_3d: 30.0
    fov_4d: 30.0
    face_spacing: 0.025
    sticker_spacing: 0.05
    enable_outline: true
  Rubiks4D:
    theta: 30.0
    phi: -35.0
    scale: 2.0
    fov_3d: 30.0
    fov_4d: 30.0
    face_spacing: 0.7
    sticker_spacing: 0.5
    enable_outline: true
colors:
  opacity: 1.0
  faces:
    Rubiks3D:
      - - 0.0
        - 0.3
        - 0.75
      - - 0.65
        - 0.75
        - 0.2
      - - 0.75
        - 0.4
        - 0.0
      - - 0.75
        - 0.0
        - 0.05
      - - 0.75
        - 0.75
        - 0.75
      - - 0.0
        - 0.6
        - 0.0
    Rubiks4D:
      - - 0.5
        - 0.2
        - 0.75
      - - 0.65
        - 0.75
        - 0.2
      - - 0.0
        - 0.6
        - 0.0
      - - 0.75
        - 0.4
        - 0.0
      - - 0.75
        - 0.0
        - 0.05
      - - 0.0
        - 0.3
        - 0.75
      - - 0.75
        - 0.75
        - 0.75
      - - 0.75
        - 0.45
        - 0.6
  background:
    - 0.3
    - 0.3
    - 0.3
  outline:
    - 0.0
    - 0.0
    - 0.0
  label_fg:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  label_bg:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
puzzle_keybinds:
  Rubiks3D:
    - sc: ShiftLeft
      command:
        hold_select:
          layers: 3
    - sc: ShiftRight
      command:
        hold_select:
          layers: 3
    - sc: KeyE
      command:
        twist:
          face: Left
          layers: 1
          direction: CCW
    - sc: KeyD
      command:
        twist:
          face: Left
          layers: 1
          direction: CW
    - sc: KeyI
      command:
        twist:
          face: Right
          layers: 1
          direction: CW
    - sc: KeyK
      command:
        twist:
          face: Right
          layers: 1
          direction: CCW
    - sc: KeyR
      command:
        twist:
          face: Left
          layers: 2
          direction: CCW
    - sc: KeyV
      command:
        twist:
          face: Left
          layers: 2
          direction: CW
    - sc: KeyU
      command:
        twist:
          face: Right
          layers: 2
          direction: CW
    - sc: KeyM
      command:
        twist:
          face: Right
          layers: 2
          direction: CCW
    - sc: KeyF
      command:
        twist:
          face: Up
          layers: 1
          direction: CCW
    - sc: KeyJ
      command:
        twist:
          face: Up
          layers: 1
          direction: CW
    - sc: KeyS
      command:
        twist:
          face: Down
          layers: 1
          direction: CW
    - sc: KeyL
      command:
        twist:
          face: Down
          layers: 1
          direction: CCW
    - sc: KeyG
      command:
        twist:
          face: Front
          layers: 1
          direction: CCW
    - sc: KeyH
      command:
        twist:
          face: Front
          layers: 1
          direction: CW
    - sc: KeyW
      command:
        twist:
          face: Back
          layers: 1
          direction: CW
    - sc: KeyO
      command:
        twist:
          face: Back
          layers: 1
          direction: CCW
    - sc: KeyT
      command:
        twist:
          face: Left
          layers: 7
          direction: CCW
    - sc: KeyB
      command:
        twist:
          face: Left
          layers: 7
          direction: CW
    - sc: KeyY
      command:
        twist:
          face: Right
          layers: 7
          direction: CW
    - sc: KeyN
      command:
        twist:
          face: Right
          layers: 7
          direction: CCW
    - sc: KeyA
      command:
        recenter:
          face: Left
    - sc: Semicolon
      command:
        recenter:
          face: Right
    - sc: KeyQ
      command:
        twist:
          face: Front
          layers: 7
          direction: CCW
    - sc: KeyP
      command:
        twist:
          face: Front
          layers: 7
          direction: CW
    - sc: KeyZ
      command:
        twist:
          face: Front
          layers: 2
          direction: CCW
    - sc: Slash
      command:
        twist:
          face: Front
          layers: 2
          direction: CW
    - sc: KeyX
      command:
        twist:
          face: Down
          layers: 2
          direction: CW
    - sc: Period
      command:
        twist:
          face: Down
          layers: 2
          direction: CCW
  Rubiks4D:
    - sc: ShiftLeft
      command:
        hold_select:
          layers: 3
    - sc: ShiftRight
      command:
        hold_select:
          layers: 3
    - sc: AltLeft
      command:
        hold_select:
          layers: 2
    - sc: AltRight
      command:
        hold_select:
          layers: 2
    - sc: KeyW
      command:
        hold_select:
          face: Left
    - sc: KeyE
      command:
        hold_select:
          face: Up
    - sc: KeyR
      command:
        hold_select:
          face: Back
    - sc: KeyS
      command:
        hold_select:
          face: Front
    - sc: KeyD
      command:
        hold_select:
          face: In
    - sc: KeyF
      command:
        hold_select:
          face: Right
    - sc: KeyC
      command:
        hold_select:
          face: Down
    - sc: KeyV
      command:
        hold_select:
          face: Out
    - sc: Digit1
      command:
        hold_select:
          piece_type: 1c
    - sc: Digit2
      command:
        hold_select:
          piece_type: 1c
    - sc: Digit3
      command:
        hold_select:
          piece_type: 1c
    - sc: Digit4
      command:
        hold_select:
          piece_type: 1c
    - sc: Digit1
      shift: true
      command:
        toggle_select:
          piece_type: 1c
    - sc: Digit2
      shift: true
      command:
        toggle_select:
          piece_type: 1c
    - sc: Digit3
      shift: true
      command:
        toggle_select:
          piece_type: 1c
    - sc: Digit4
      shift: true
      command:
        toggle_select:
          piece_type: 1c
    - sc: Escape
      command:
        clear_toggle_select: piece_type
    - sc: KeyI
      command:
        twist:
          layers: 1
          direction: x
    - sc: KeyK
      command:
        twist:
          layers: 1
          direction: "x'"
    - sc: KeyJ
      command:
        twist:
          layers: 1
          direction: y
    - sc: KeyL
      command:
        twist:
          layers: 1
          direction: "y'"
    - sc: KeyU
      command:
        twist:
          layers: 1
          direction: "z'"
    - sc: KeyO
      command:
        twist:
          layers: 1
          direction: z
    - sc: Space
      command:
        recenter: {}
    - sc: KeyT
      command:
        twist:
          face: In
          layers: 7
          direction: x
    - sc: KeyY
      command:
        twist:
          face: In
          layers: 7
          direction: x
    - sc: KeyB
      command:
        twist:
          face: In
          layers: 7
          direction: "x'"
    - sc: KeyN
      command:
        twist:
          face: In
          layers: 7
          direction: "x'"
    - sc: KeyA
      command:
        twist:
          face: In
          layers: 7
          direction: "y'"
    - sc: Semicolon
      command:
        twist:
          face: In
          layers: 7
          direction: y
    - sc: KeyQ
      command:
        twist:
          face: In
          layers: 7
          direction: "z'"
    - sc: KeyP
      command:
        twist:
          face: In
          layers: 7
          direction: z
