---
gfx:
  msaa: true
view:
  Rubiks3D:
    pitch: 35.0
    yaw: -20.0
    scale: 1.25
    fov_3d: 30.0
    fov_4d: 30.0
    face_spacing: 0.025
    sticker_spacing: 0.05
    outline_thickness: 2.0
    light_intensity: 0.0
    light_pitch: 0.0
    light_yaw: 0.0
  Rubiks4D:
    pitch: 30.0
    yaw: -35.0
    scale: 2.0
    fov_3d: 30.0
    fov_4d: 30.0
    face_spacing: 0.7
    sticker_spacing: 0.3
    outline_thickness: 1.0
    light_intensity: 1.0
    light_pitch: 65.0
    light_yaw: -55.0
outlines:
  default_size: 1.0
  hidden_size: 0.0
  hovered_size: 1.0
  default_color: "#000000"
  hidden_color: "#000000"
  hovered_color: "#ffffff"
colors:
  default_opacity: 1.0
  hidden_opacity: 0.3
  hovered_opacity: 1.0
  background: "#444444"
  blind_face: "#cccccc"
  blindfold: false
  faces:
    Rubiks3D:
      B: "#4488ff"
      D: "#ffff00"
      L: "#ff9922"
      R: "#cc3333"
      U: "#ffffff"
      F: "#66cc44"
    Rubiks4D:
      I: "#8822cc"
      B: "#ffff00"
      D: "#88ee66"
      L: "#ff9922"
      R: "#cc3333"
      U: "#33aaff"
      F: "#ffffff"
      O: "#ff66ff"
interaction:
  confirm_discard_only_when_scrambled: true
  highlight_piece_on_hover: true
  selection_fade_duration: 0.1
  hover_fade_duration: 0.1
  twist_duration: 0.2
  dynamic_twist_speed: true
general_keybinds:
  - vk: O
    ctrl: true
    command: open
  - vk: S
    ctrl: true
    command: save
  - vk: S
    ctrl: true
    shift: true
    command: save_as
  - vk: Q
    ctrl: true
    command: exit
  - vk: Z
    ctrl: true
    command: undo
  - vk: Z
    ctrl: true
    shift: true
    command: redo
  - vk: Y
    ctrl: true
    command: redo
  - vk: R
    ctrl: true
    command: reset
  - vk: B
    ctrl: true
    command: toggle_blindfold
  - vk: F
    ctrl: true
    command: scramble_full
  - vk: F3
    command:
      new_puzzle:
        Rubiks3D:
          layer_count: 3
  - vk: F4
    command:
      new_puzzle:
        Rubiks4D:
          layer_count: 3
puzzle_keybinds:
  Rubiks3D:
    - sc: ShiftLeft
      command:
        select_layers: 3
    - sc: ShiftRight
      command:
        select_layers: 3
    - sc: KeyE
      command:
        twist:
          axis: L
          direction: CCW
          layers: 1
    - sc: KeyD
      command:
        twist:
          axis: L
          direction: CW
          layers: 1
    - sc: KeyI
      command:
        twist:
          axis: R
          direction: CW
          layers: 1
    - sc: KeyK
      command:
        twist:
          axis: R
          direction: CCW
          layers: 1
    - sc: KeyR
      command:
        twist:
          axis: L
          direction: CCW
          layers: 2
    - sc: KeyV
      command:
        twist:
          axis: L
          direction: CW
          layers: 2
    - sc: KeyU
      command:
        twist:
          axis: R
          direction: CW
          layers: 2
    - sc: KeyM
      command:
        twist:
          axis: R
          direction: CCW
          layers: 2
    - sc: KeyF
      command:
        twist:
          axis: U
          direction: CCW
          layers: 1
    - sc: KeyJ
      command:
        twist:
          axis: U
          direction: CW
          layers: 1
    - sc: KeyS
      command:
        twist:
          axis: D
          direction: CW
          layers: 1
    - sc: KeyL
      command:
        twist:
          axis: D
          direction: CCW
          layers: 1
    - sc: KeyG
      command:
        twist:
          axis: F
          direction: CCW
          layers: 1
    - sc: KeyH
      command:
        twist:
          axis: F
          direction: CW
          layers: 1
    - sc: KeyW
      command:
        twist:
          axis: B
          direction: CW
          layers: 1
    - sc: KeyO
      command:
        twist:
          axis: B
          direction: CCW
          layers: 1
    - sc: KeyT
      command:
        twist:
          axis: L
          direction: CCW
          layers: 7
    - sc: KeyB
      command:
        twist:
          axis: L
          direction: CW
          layers: 7
    - sc: KeyY
      command:
        twist:
          axis: R
          direction: CW
          layers: 7
    - sc: KeyN
      command:
        twist:
          axis: R
          direction: CCW
          layers: 7
    - sc: KeyA
      command:
        recenter:
          axis: L
    - sc: Semicolon
      command:
        recenter:
          axis: R
    - sc: KeyQ
      command:
        twist:
          axis: F
          direction: CCW
          layers: 7
    - sc: KeyP
      command:
        twist:
          axis: F
          direction: CW
          layers: 7
    - sc: KeyZ
      command:
        twist:
          axis: F
          direction: CCW
          layers: 2
    - sc: Slash
      command:
        twist:
          axis: F
          direction: CW
          layers: 2
    - sc: KeyX
      command:
        twist:
          axis: D
          direction: CW
          layers: 2
    - sc: Period
      command:
        twist:
          axis: D
          direction: CCW
          layers: 2
  Rubiks4D:
    - sc: ShiftLeft
      command:
        select_layers: 3
    - sc: ShiftRight
      command:
        select_layers: 3
    - sc: AltLeft
      command:
        select_layers: 2
    - sc: AltRight
      command:
        select_layers: 2
    - sc: KeyW
      command:
        select_axis: Left
    - sc: KeyE
      command:
        select_axis: Up
    - sc: KeyR
      command:
        select_axis: Back
    - sc: KeyS
      command:
        select_axis: Front
    - sc: KeyD
      command:
        select_axis: In
    - sc: KeyF
      command:
        select_axis: Right
    - sc: KeyC
      command:
        select_axis: Down
    - sc: KeyV
      command:
        select_axis: Out
    - sc: Digit1
      command:
        select_layers: 1
    - sc: Digit2
      command:
        select_layers: 2
    - sc: Digit3
      command:
        select_layers: 4
    - sc: Digit4
      command:
        select_layers: 8
    - sc: Digit5
      command:
        select_layers: 16
    - sc: Digit6
      command:
        select_layers: 32
    - sc: Digit7
      command:
        select_layers: 64
    - sc: Digit8
      command:
        select_layers: 128
    - sc: Digit9
      command:
        select_layers: 256
    - sc: KeyI
      command:
        twist:
          direction: x
          layers: 1
    - sc: KeyK
      command:
        twist:
          direction: "x'"
          layers: 1
    - sc: KeyJ
      command:
        twist:
          direction: y
          layers: 1
    - sc: KeyL
      command:
        twist:
          direction: "y'"
          layers: 1
    - sc: KeyU
      command:
        twist:
          direction: "z'"
          layers: 1
    - sc: KeyO
      command:
        twist:
          direction: z
          layers: 1
    - sc: Space
      command:
        recenter: {}
    - sc: KeyT
      command:
        twist:
          axis: I
          direction: x
          layers: 7
    - sc: KeyY
      command:
        twist:
          axis: I
          direction: x
          layers: 7
    - sc: KeyB
      command:
        twist:
          axis: I
          direction: "x'"
          layers: 7
    - sc: KeyN
      command:
        twist:
          axis: I
          direction: "x'"
          layers: 7
    - sc: KeyA
      command:
        twist:
          axis: I
          direction: "y'"
          layers: 7
    - sc: Semicolon
      command:
        twist:
          axis: I
          direction: y
          layers: 7
    - sc: KeyQ
      command:
        twist:
          axis: I
          direction: "z'"
          layers: 7
    - sc: KeyP
      command:
        twist:
          axis: I
          direction: z
          layers: 7
info:
  metric: STM
  keybinds_reference:
    function: false
    navigation: false
    numpad: false
    opacity: 1.0
